name: alhaddad_driver
version: 4.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  package_info_plus: ^1.4.2
  get_storage: ^2.0.3
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  intl: ^0.17.0
  pretty_dio_logger: ^1.2.0-beta-1
  google_fonts: ^2.3.1
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.20
  pin_input_text_field: ^4.1.2
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  maps_launcher: ^2.0.1


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sample_jsons/

